### ISSUE TITLE
Make this a template repo

### ISSUE THREAD

**Issue by davidsneighbour** [zwbetz-gh/make-a-hugo-blog-from-scratch#1]
Just to be "perfect" with the whole "blog from scratch" thingy :+1: 

Go to the settings tab and look for a checkbox to make this a template repo. This will result in no history being created when somebody forks your repo and pull requests in subsequent forks being attributed to the respective fork, not the original repo.

**Comment by zwbetz-gh** [comment]
I like the idea. It is done.
