### ISSUE TITLE
default favicon

### ISSUE THREAD

**Issue by chunyunma** [zwbetz-gh/make-a-hugo-blog-from-scratch#3]
I noticed that a default favicon (a letter "H" with a pink background) would be generated 
and placed inside folder `public` each time I run `hugo` locally.
I inspected all the config files and could not see where this default behaviour originated.
Is there anyway to override this default favicon and use my own?

I have tried the following to use customized favicons, with no success:

- generate favicon using `https://realfavicongenerator.net`
- place `favicon.png` inside `static/favicon/`
- modify `head.html` by adding `<link rel="icon" type="image/png" href="/favicon/favicon.png">`

Thank you!

**Comment by zwbetz-gh** [comment]
The default favicon lives at https://github.com/zwbetz-gh/make-a-hugo-blog-from-scratch/blob/master/static/favicon.ico

To change it, just put a new file there with the same name.
